apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: "EnsureExists"
  name: elb
  namespace: kube-system
spec:
  ports:
  - port: 8765
    targetPort: 9376
  selector:
    app: "<kuberneteselbsvcname>"
  type: LoadBalancer