---
# FIXME: Anything below in all-caps has it's value replaced by sed in the
#        openshiftmasterscript.sh which is not ideal, we should fix that.
localmaster:
  hosts:
    localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: /usr/bin/python2

    openshift_is_containerized: False
    openshift_client_binary: /usr/bin/oc

    openshift_image_tag: "vVERSION"

    openshift_web_console_image_name: "IMAGE_PREFIX/IMAGE_TYPE-web-console:vVERSION"

    oreg_url: 'IMAGE_PREFIX/IMAGE_TYPE-${component}:${version}'
    openshift_master_default_subdomain: 'TEMPROUTERIP.nip.io'

    # FIXME
    # This should be type=infra, but we have to live with region=infra for now
    # because of legacy reasons
    openshift_router_selector: 'region=infra'
    openshift_registry_selector: 'region=infra'
    # No idea why this is a different data type, but it is
    openshift_prometheus_node_selector: {'region': 'infra'}

    # Set Azure specific data for hosted registry
    openshift_hosted_registry_storage_provider: "azure_blob"
    openshift_hosted_registry_storage_kind: "object"
    openshift_hosted_registry_storage_azure_blob_accountname: 'REGISTRY_STORAGE_AZURE_ACCOUNTNAME'
    openshift_hosted_registry_storage_azure_blob_accountkey: 'REGISTRY_STORAGE_AZURE_ACCOUNTKEY'
    openshift_hosted_registry_storage_azure_blob_container: "registry"
    openshift_hosted_registry_storage_azure_blob_realm: "core.windows.net"

    # FIXME
    #
    # Hard code this for now.
    #
    # Currently the cluster state at deployment time does not have the nodes
    # registered to the master with labels applied and ready to be queried
    # against at the point in time in the deploy that the playbooks run. Also,
    # the router replica count default "falls back" to 1 appropriately where as
    # the registry replica logic does not. There was also discussion about if
    # it's appropriate to do this with replicas == infra nodes because it's
    # perfectly feasible to have an infra node count higher than the desired
    # replicas.
    #
    # Revisit later (possibly a daemonset or $other)
    openshift_hosted_router_replicas: 1
    openshift_hosted_registry_replicas: 1

    openshift_prometheus_state: "present"
    openshift_prometheus_node_exporter_image_version: 'PROMETHEUS_EXPORTER_VERSION'

    openshift_web_console_install: True

    openshift_prometheus_image_prefix: "IMAGE_PREFIX/"
    openshift_deployment_type: 'ANSIBLE_DEPLOY_TYPE'

    ansible_service_broker_install: True
    openshift_service_catalog_image: "IMAGE_PREFIX/IMAGE_TYPE-service-catalog:vVERSION"
    openshift_master_etcd_urls: ["https://HOSTNAME:2379"]

    template_service_broker_image: "IMAGE_PREFIX/IMAGE_TYPE-template-service-broker:vVERSION"

    # NOTE: This is redundant, but required to handle version skew between
    #       openshift-ansible in Origin and OCP
    openshift_examples_content_version: "vSHORT_VER"

    openshift_cockpit_deployer_prefix: "COCKPIT_PREFIX/"
    openshift_cockpit_deployer_basename: "COCKPIT_BASENAME"
    openshift_cockpit_deployer_version: "COCKPIT_VERSION"

    # NOTE: Do not define openshift_hosted_router_replicas so that the task file
    # router.yml inside the openshift_hosted role from openshift-ansible will
    # autopopulate it using the openshift_hosted_router_selector and querying
    # the number of infra nodes

    # NOTE: The variables below are internal to openshift-ansible and we're
    #       providing them here to avoid the incurred cost of fact finding
    openshift:
      common:
        config_base: /etc/origin/
        examples_content_version: "vSHORT_VER"
      master:
        public_console_url: "https://{{ .ExternalMasterHostname }}:8443/console"
        public_api_url: "https://{{ .ExternalMasterHostname }}:8443"
        etcd_urls: ["https://HOSTNAME:2379"] #FIXME: No longer needed as of openshift-ansible-3.9.22-1 but we're not on that version yet
      node:
        nodename: 'HOSTNAME'

oo_masters_to_config:
  hosts:
    localhost
