- name: Deploy OpenShift infrastructure workload
  hosts: localmaster
  gather_facts: false

  tasks:
    - name: Import openshift_bootstrap_autoapprover role from openshift-ansible to deploy node bootstrap auto approver
      import_role:
        name: openshift_bootstrap_autoapprover

    - name: Import and use router task file from openshift-ansible openshift_hosted role
      import_role:
        name: openshift_hosted
        tasks_from: router.yml

    - name: Import and use registry task file from openshift-ansible openshift_hosted role
      import_role:
        name: openshift_hosted
        tasks_from: registry.yml

    - name: Import openshift_web_console role from openshift-ansible to deploy web console
      import_role:
        name: openshift_web_console

    # FIXME - There's a race condition where the infra label isn't applied to
    #         the infra node during cluster bring up in
    #         openshift_bootstrap_autoapprover, this is problematic because the
    #         openshift_prometheus role checks to ensure there is a node with
    #         the infra selector up/available/schedulable.
    - shell: '/usr/bin/oc get nodes -l "region=infra" | wc -l'
      register: result
      until: result.stdout_lines[0]|int > 1
      retries: 30
      delay: 10


    - name: Import openshift_prometheus role from openshift-ansible to deploy prometheus
      import_role:
        name: openshift_prometheus

    - name: Import openshift_service_catalog role from openshift-ansible to deploy the service catalog
      import_role:
        name: openshift_service_catalog

    - name: Import ansible_service_broker role from openshift-ansible to deploy the ansible service broker
      import_role:
        name: ansible_service_broker

    - name: Import template_service_broker role from openshift-ansible to deploy the template service broker
      import_role:
        name: template_service_broker

    - name: Import openshift_examples role from openshift-ansible to deploy the examples
      import_role:
        name: openshift_examples

    - name: Import openshift_hosted_templates role from openshift-ansible to deploy the hosted templates
      import_role:
        name: openshift_hosted_templates

    - name: Import cockpit_ui role from openshift-ansible to deploy the registry console
      import_role:
        name: cockpit-ui
